import Head from 'next/head'
import { ReactNode } from 'react'
import Header from '@/components/ui/header'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Nextjs Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="container mx-auto p-4">{children}</main>
    </>
  )
}
