import Head from 'next/head'
import { ReactNode } from 'react'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Nextjs Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100  ">
        <header className="w-full bg-red-300 shadow-md p-10">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-lg font-bold">ShareLink</h1>
          </div>
        </header>
        <main className="p-4 ">
          <div className="container mx-auto">{children}</div>
        </main>
      </div>
    </>
  )
}
